project:
  type: website
  resources:
    - "pdf/*.pdf"
    - "images/*"

website:
  title: "PEG study training"
  bread-crumbs: true
  back-to-top-navigation: true
  reader-mode: true
  
  navbar:
    left:
      - icon: house-fill
        text: Home
        href: index.qmd
      - icon: calendar-check-fill
        text: Timeline
        href: timeline.qmd
      - icon: info-circle-fill
        text: About
        href: about.qmd
    right:
      - icon: github
        url: https://ivangong24.github.io/
      - icon: browser-safari
        text: PEG Study website
        url: https://www.pegstudy.com/
          
  sidebar:
    style: "floating"
    contents: auto
    

      
execute:
  freeze: auto

format:
  html:
    theme: 
      light: litera
      dark: slate
    css: styles.css
    toc: true
    